### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by okwme** [peter-featherstone/Ubuntu-Crypto-Price-Ticker#3]
Install seems to work but running `make` or `python3 app/main.py` afterwards gives this error:
```
app/main.py:7: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
Traceback (most recent call last):
  File "app/main.py", line 8, in <module>
    from menu import Menu
  File "/home/billyrennekamp/GitHub.com/peter-featherstone/Ubuntu-Crypto-Price-Ticker/app/menu.py", line 6, in <module>
    from gi.repository import AppIndicator3, Gtk, GdkPixbuf
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 133, in load_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name AppIndicator3, introspection typelib not found
```

**Comment by paras-lehana** [comment]
Hi @okwme,

It seems that you need to install [AppIndicator](https://packages.ubuntu.com/xenial/gir1.2-appindicator3-0.1). 

This repo required me install and update many packages but it was worth it. I need we need a README for requisites. @peter-featherstone

**Comment by peter-featherstone** [comment]
Hey @paras-lehana it may be worth you taking over this project now as I don't have an Ubunut machine anymore so it's impossible for me to debug issues.

**Comment by paras-lehana** [comment]
No issues, @peter-featherstone. I'll try to keep the repo active. :)
